// <auto-generated />
using FileManagement.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileManagement.Migrations
{
    [DbContext(typeof(FileManagementContext))]
    [Migration("20260813120312_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileManagement.Entity.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContentType = "image/jpg",
                            Extension = ".jpg",
                            IsDeleted = false,
                            Length = 52501m,
                            Name = "68a1a7ccdfe3241d0aa9f9ae_REF23",
                            Path = "C:/inetpub/api/FileManagement\\Uploads/Avatars\\68a1a7ccdfe3241d0aa9f9ae_REF23.jpg"
                        },
                        new
                        {
                            Id = 2L,
                            ContentType = "image/jpg",
                            Extension = ".jpg",
                            IsDeleted = false,
                            Length = 52501m,
                            Name = "68a1a7ccdfe3241d0aa9f9ae_REF28",
                            Path = "C:/inetpub/api/FileManagement\\Uploads/Avatars\\68a1a7ccdfe3241d0aa9f9ae_REF28.jpg"
                        },
                        new
                        {
                            Id = 3L,
                            ContentType = "image/jpg",
                            Extension = ".jpg",
                            IsDeleted = false,
                            Length = 52501m,
                            Name = "68a1a7ccdfe3241d0aa9f9ae_REF29",
                            Path = "C:/inetpub/api/FileManagement\\Uploads/Avatars\\68a1a7ccdfe3241d0aa9f9ae_REF29.jpg"
                        },
                        new
                        {
                            Id = 4L,
                            ContentType = "image/jpg",
                            Extension = ".jpg",
                            IsDeleted = false,
                            Length = 270336m,
                            Name = "68a1a7ccdfe3241d0aa9f9ae_REF22",
                            Path = "C:/inetpub/api/FileManagement\\Uploads/Articles\\68a1a7ccdfe3241d0aa9f9ae_REF22.jpg"
                        },
                        new
                        {
                            Id = 5L,
                            ContentType = "image/jpg",
                            Extension = ".jpg",
                            IsDeleted = false,
                            Length = 270336m,
                            Name = "68a1a8006928f76bab0bf47d_REF19",
                            Path = "C:/inetpub/api/FileManagement\\Uploads/Articles\\68a1a8006928f76bab0bf47d_REF19.jpg"
                        },
                        new
                        {
                            Id = 6L,
                            ContentType = "image/jpg",
                            Extension = ".jpg",
                            IsDeleted = false,
                            Length = 270336m,
                            Name = "68a1a990b816e33cfbd857ea_REF5",
                            Path = "C:/inetpub/api/FileManagement\\Uploads/Articles\\68a1a990b816e33cfbd857ea_REF5.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
