// <auto-generated />
using FileManagement.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileManagement.Migrations
{
    [DbContext(typeof(FileManagementContext))]
    partial class FileManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileManagement.Entity.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContentType = "image/jpeg",
                            Extension = ".jpeg",
                            IsDeleted = false,
                            Length = 52501m,
                            Name = "Queenie",
                            Path = "C:\\Users\\Asus\\Desktop\\RIPMyFriend-Backend\\FileManagement\\Uploads/Memories\\Queenie.jpeg"
                        },
                        new
                        {
                            Id = 2L,
                            ContentType = "image/jpeg",
                            Extension = ".jpeg",
                            IsDeleted = false,
                            Length = 12481m,
                            Name = "Ringo",
                            Path = "C:\\Users\\Asus\\Desktop\\RIPMyFriend-Backend\\FileManagement\\Uploads/Memories\\Ringo.jpeg"
                        },
                        new
                        {
                            Id = 3L,
                            ContentType = "image/jpeg",
                            Extension = ".jpeg",
                            IsDeleted = false,
                            Length = 118784m,
                            Name = "Bubbles",
                            Path = "C:\\Users\\Asus\\Desktop\\RIPMyFriend-Backend\\FileManagement\\Uploads/Memories\\Bubbles.jpeg"
                        },
                        new
                        {
                            Id = 4L,
                            ContentType = "image/jpeg",
                            Extension = ".jpeg",
                            IsDeleted = false,
                            Length = 276500m,
                            Name = "George",
                            Path = "C:\\Users\\Asus\\Desktop\\RIPMyFriend-Backend\\FileManagement\\Uploads/Memories\\George.jpeg"
                        },
                        new
                        {
                            Id = 5L,
                            ContentType = "image/jpeg",
                            Extension = ".jpeg",
                            IsDeleted = false,
                            Length = 542177m,
                            Name = "George(1)",
                            Path = "C:\\Users\\Asus\\Desktop\\RIPMyFriend-Backend\\FileManagement\\Uploads/Memories\\George(1).jpeg"
                        },
                        new
                        {
                            Id = 6L,
                            ContentType = "image/jpeg",
                            Extension = ".jpeg",
                            IsDeleted = false,
                            Length = 270336m,
                            Name = "George(2)",
                            Path = "C:\\Users\\Asus\\Desktop\\RIPMyFriend-Backend\\FileManagement\\Uploads/Memories\\George(2).jpeg"
                        },
                        new
                        {
                            Id = 7L,
                            ContentType = "image/jpg",
                            Extension = ".jpg",
                            IsDeleted = false,
                            Length = 270336m,
                            Name = "68a1a7ccdfe3241d0aa9f9ae_REF22",
                            Path = "C:\\Users\\Asus\\Desktop\\RIPMyFriend-Backend\\FileManagement\\Uploads/Articles\\68a1a7ccdfe3241d0aa9f9ae_REF22.jpg"
                        },
                        new
                        {
                            Id = 8L,
                            ContentType = "image/jpg",
                            Extension = ".jpg",
                            IsDeleted = false,
                            Length = 270336m,
                            Name = "68a1a8006928f76bab0bf47d_REF19",
                            Path = "C:\\Users\\Asus\\Desktop\\RIPMyFriend-Backend\\FileManagement\\Uploads/Articles\\68a1a8006928f76bab0bf47d_REF19.jpg"
                        },
                        new
                        {
                            Id = 9L,
                            ContentType = "image/jpg",
                            Extension = ".jpg",
                            IsDeleted = false,
                            Length = 270336m,
                            Name = "68a1a990b816e33cfbd857ea_REF5",
                            Path = "C:\\Users\\Asus\\Desktop\\RIPMyFriend-Backend\\FileManagement\\Uploads/Articles\\68a1a990b816e33cfbd857ea_REF5.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
