// <auto-generated />
using FAQManagement.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FAQManagement.Migrations
{
    [DbContext(typeof(FAQManagementContext))]
    [Migration("20260813120330_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FAQManagement.Entity.FAQ", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "<p>Bir anı sayfası; kaybettiğiniz, ömrünü ömrünüze katmış o can dostunuzun ardından evde açılan o sessiz ama en kıymetli köşe gibidir. Onun hayat hikayesini, size kattığı neşeyi ve aranızdaki o benzersiz bağı korumanın en temiz, en kalıcı yoludur</p>\r\n<p>Burada, onunla geçen o güzel günlerin fotoğraflarını ve videolarını bir araya getirebilir, altlarına kalbinizden dökülen en içten anıları yazabilirsiniz. Sevdiklerinizle bu sayfayı paylaşarak onlardan da dostunuzla ilgili güzel taziye mesajları ve hatıralar toplayabilirsiniz</p>\r\n<p><strong>Styever anı sayfaları</strong>,  sosyal medyanın o karmaşık ve gelip geçici akışından çok uzak, sadece dostunuzun adına açılmış kalıcı bir hatıra albümüdür. Çünkü onlar hayatımızdan çıksalar bile, bıraktıkları izlerin her zaman korunmayı hak ettiğine inanıyoruz</p>",
                            ContentEn = "<p>A memorial page is like that quiet yet most precious corner of your home created after losing the beloved companion who shared their life with yours. It is the purest and most lasting way to preserve their life story, the joy they brought you, and the unique bond you shared.</p>\r\n<p>Here, you can bring together the photos and videos from those beautiful days you spent with them, and write the most heartfelt memories beneath them. By sharing this page with your loved ones, you can also collect meaningful condolence messages and memories about your companion.</p>\r\n<p><strong>Styever memorial pages</strong> are a permanent memory album created only in your companion’s name, far away from the complicated and fleeting flow of social media. Because we believe that even after they leave our lives, the traces they leave behind always deserve to be preserved.</p>",
                            Header = "Bir \"Anı Sayfası\" tam olarak ne demek?",
                            HeaderEn = "What exactly is a \"Memorial Page\"?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2L,
                            Content = "<p>Hayır, Styever belirli bir ücretlendirme modeliyle çalışır.</p><p>Sevdiklerinizin anılarını uzun yıllar boyunca güvenle saklayabilmemiz için aşağıdaki operasyonel giderlerimiz bulunmaktadır:</p><ul><li>Yüksek kapasiteli veri depolama,</li><li>Fotoğraf ve video barındırma,</li><li>Teknik altyapı sürekliliği,</li><li>Sistem bakım maliyetleri.</li></ul><p>Dostlarınızın anı sayfalarının kesintisiz bir şekilde yayında kalmasını sağlamak ve sunduğumuz dijital deneyimi her geçen gün geliştirmek amacıyla bu sürdürülebilir ücretlendirme modelini uyguluyoruz.</p>",
                            ContentEn = "<p>No, Styever operates with a paid service model.</p><p>In order to securely preserve the memories of your loved ones for many years, we have operational costs such as:</p><ul><li>High-capacity data storage,</li><li>Photo and video hosting,</li><li>Technical infrastructure continuity,</li><li>Ongoing system maintenance.</li></ul><p>We apply this sustainable pricing model to ensure that your companions’ memorial pages remain continuously accessible and to keep improving the digital experience we provide every day.</p>",
                            Header = "Styever hizmetleri ücretsiz mi?",
                            HeaderEn = "Are Styever services free of charge?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3L,
                            Content = "<p>Anı sayfanız, bağlantıya sahip olan herkes tarafından ziyaret edilebilir.</p><p>Sayfanızın linkini ailenizle, arkadaşlarınızla veya dostunuzu tanıyan herkesle paylaşarak bu özel hatıranın büyümesine vesile olabilirsiniz.</p><p>Paylaştığınız link sayesinde sevdikleriniz de sayfayı ziyaret edebilir, anıları okuyabilir ve dijital bir mum yakarak bu sevgiye ortak olabilir.</p>",
                            ContentEn = "<p>Your memorial page can be visited by anyone who has the link.</p><p>By sharing your page with family members, friends, or anyone who knew your beloved companion, you can help this special memory continue to grow.</p><p>Through the shared link, your loved ones can visit the page, read the memories, and join in this act of love by lighting a digital candle.</p>",
                            Header = "Anma sayfamı kimler görebilir?",
                            HeaderEn = "Who can see my memorial page?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4L,
                            Content = "<p>Evet, dilediğiniz an iptal edebilirsiniz.</p><p><strong>Styever, kullanıcılarına herhangi bir taahhüt veya zorunluluk sunmaz.</strong></p><p>Kontrol tamamen sizdedir; dilediğiniz zaman hesap ayarlarınız üzerinden aboneliğinizi sonlandırabilirsiniz.</p><p>İptal işleminizden sonra, o ay için geçerli olan haklarınız dönem sonuna kadar devam eder ve bir sonraki dönem için yeni bir ödeme alınmaz.</p>",
                            ContentEn = "<p>Yes, you may cancel at any time.</p><p><strong>Styever does not impose any commitments or obligations on its users.</strong></p><p>You remain fully in control and can end your subscription whenever you wish through your account settings.</p><p>After cancellation, your current membership benefits will remain active until the end of the billing period, and no new payment will be charged for the following period.</p>",
                            Header = "Aboneliği istediğim zaman iptal edebilir miyim?",
                            HeaderEn = "Can I cancel my subscription at any time?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5L,
                            Content = "<p>Hayır, anı sayfanız yayında kalmaya devam eder.</p><p>Üyeliğiniz sona erdiğinde yalnızca aşağıdaki güncelleme yetkileri kısıtlanır:</p><ul><li>Yeni fotoğraf ekleme,</li><li>Mevcut metinleri düzenleme,</li><li>Sayfa içeriğini güncelleme.</li></ul><p>Ancak dostunuzun hatırası dijital dünyadaki yerini korur.</p><p>Eğer sayfanın tamamen kaldırılmasını isterseniz, kayıtlı e-posta adresiniz ve sayfa isminizle birlikte <strong>info@styever.com</strong> üzerinden bize ulaşabilirsiniz.</p><p>Talebiniz doğrultusunda ilgili sayfa en geç <strong>48 saat</strong> içerisinde sistemimizden tamamen silinecektir.</p>",
                            ContentEn = "<p>No, your memorial page will remain published and accessible.</p><p>When your membership ends, only update permissions will be restricted, such as:</p><ul><li>Adding new photos,</li><li>Editing existing texts,</li><li>Updating page content.</li></ul><p>However, your companion’s memory will continue to have its place in the digital world.</p><p>If you would like the page to be completely removed, you may contact us at <strong>info@styever.com</strong> using your registered email address and the name of the memorial page.</p><p>In line with your request, the relevant page will be permanently deleted from our system within <strong>48 hours</strong> at the latest.</p>",
                            Header = "Üyeliğimi iptal edersem anı sayfam silinir mi?",
                            HeaderEn = "Will my memorial page be deleted if I cancel my membership?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6L,
                            Content = "<p>Styever, her ihtiyaca ve her anıya uygun üç farklı abonelik seçeneği sunar:</p><ul><li><strong>Origin Paketi:</strong> Sade ve anlamlı bir hatıra bırakmak isteyenler için tasarlandı. Tek bir özel fotoğraf ve biyografi alanı ile dostunuzun temel bilgilerini ve hatırasını dijital dünyada ölümsüzleştirebilirsiniz.</li><li><strong>Heart Paketi:</strong> Daha derin bir hikâye anlatmak isteyenler için idealdir. Birden fazla fotoğraf, video galerisi, kapsamlı bir biyografi bölümü ve YouTube içerikleriyle dostunuzun yaşam yolculuğunu tüm detaylarıyla paylaşmanıza imkan tanır.</li><li><strong>Family Paketi:</strong> Birden fazla dostunu aynı anda anmak isteyen büyük aileler için en kapsamlı seçeneğimizdir. Bu paketle dört ayrı anı sayfası oluşturabilir; her dostunuz için bağımsız galeriler, hikâyeler ve dijital alanlar tanımlayabilirsiniz.</li></ul>",
                            ContentEn = "<p>Styever offers three different subscription options designed to suit every need and every memory:</p><ul><li><strong>Origin Package:</strong> Designed for those who wish to leave a simple yet meaningful tribute. With a single special photo and a biography section, you can immortalize your companion’s essential information and memory in the digital world.</li><li><strong>Heart Package:</strong> Ideal for those who want to tell a deeper story. With multiple photos, a video gallery, an extended biography section, and YouTube content integration, you can share your companion’s life journey in full detail.</li><li><strong>Family Package:</strong> Our most comprehensive option for large families who wish to honor more than one companion at the same time. With this package, you can create four separate memorial pages and define independent galleries, stories, and digital spaces for each of your beloved companions.</li></ul>",
                            Header = "Planlar arasındaki fark ne?",
                            HeaderEn = "What's the difference between the plans?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7L,
                            Content = "<p>Elbette.</p><p>Aradan ne kadar zaman geçmiş olursa olsun, <strong>sevgi eskimez</strong>.</p><p>Hazır hissettiğiniz gün Styever’da sayfayı açabilir, onun izini kalıcılaştırabilirsiniz.</p>",
                            ContentEn = "<p>Of course.</p><p>No matter how much time passes, <strong>love never fades</strong>.</p><p>Whenever you feel ready, you can open a new page on Styever and immortalize your companion’s memory.</p>",
                            Header = "Yıllar önce kaybettiğim pet için de anma oluşturabilir miyim?",
                            HeaderEn = "Can I also create a memorial for my pet that I lost years ago?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8L,
                            Content = "<p>Styever’da ödemeler tek seferliktir.</p><p>Anma sayfasını oluşturduğunuzda sayfa size ait olur.</p><p>Ayrıca <strong>12 ay boyunca</strong> sayfanızı özgürce düzenleyebilir, yeni fotoğraflar ekleyebilir ve dilediğinizde yeniden şekillendirebilirsiniz.</p><p>Bu sürenin sonunda düzenleme hakkı sona erer; ancak anı sayfanız yayında kalmaya devam eder.</p><p>Sayfanızı dilediğiniz gibi düzenlemeye devam etmek isterseniz aboneliğinizi yenileyebilirsiniz.</p>",
                            ContentEn = "<p>At Styever, payments are one-time only.</p><p>Once you create your memorial page, it becomes yours.</p><p>You can also freely edit your page, add new photos, and reshape it as you wish for <strong>12 months</strong>.</p><p>At the end of this period, your editing rights expire; however, your memorial page remains live.</p><p>If you want to continue editing your page as you wish, you can renew your subscription.</p>",
                            Header = "Ödeme modeli nasıl işliyor?",
                            HeaderEn = "How does the payment model work?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9L,
                            Content = "<p>Evet.</p><p><strong>12 aylık düzenleme süresi boyunca</strong> sayfayı dilediğiniz kadar yenileyebilir, anılar ekleyebilir ve anlatımınızı derinleştirebilirsiniz.</p>",
                            ContentEn = "<p>Yes.</p><p>During the <strong>12-month editing period</strong>, you can refresh the page as much as you want, add memories, and deepen your narrative.</p>",
                            Header = "Daha sonra düzenleme yapabilir miyim?",
                            HeaderEn = "Can I make changes later?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10L,
                            Content = "<p>Evet.</p><p>Origin ya da Heart Paketlerinden biri ile başladığınızda, daha sonra planınızı yükseltip daha kapsamlı bir anı alanına geçebilirsiniz.</p>",
                            ContentEn = "<p>Yes.</p><p>When you start with either a Origin or Heart Package, you can later upgrade your plan to a more comprehensive memorial package.</p>",
                            Header = "Planımı sonradan yükseltebilir miyim?",
                            HeaderEn = "Can I upgrade my plan later?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11L,
                            Content = "<p>Evet — özellikle <strong>Family Paketi</strong> bunun için tasarlanmıştır.</p><p>Aynı hesapla dört farklı dostunuz için dört ayrı anma sayfası oluşturabilir, her birine özel bir hikâye alanı ayırabilirsiniz.</p>",
                            ContentEn = "<p>Yes — the <strong>Family Package</strong> is specifically designed for this.</p><p>With the same account, you can create four separate memorial pages for four different companions and dedicate a unique story space to each of them.</p>",
                            Header = "Birden fazla can dostum için anma sayfası açabilir miyim?",
                            HeaderEn = "Can I create memorial pages for more than one best friend?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12L,
                            Content = "<p>Styever olarak, kayıp dostlarımızın ardından tutulan yası ve özlemi hafifletmenin en güzel yolunun, o güzel hatıraları sevdiklerimizle birlikte yaşatmak olduğuna inanıyoruz. Platformumuzda yer alan <strong>Mum Yakma</strong> ve <strong>anı bırakma</strong> özellikleri, dostunuzun sayfasını ziyaret eden herkesin katılabileceği kalıcı bir anma ritüelidir.</p>\r\n<p><strong>Süreç Nasıl İşler?</strong> Ziyaretçiler, dostunuzun anı sayfasına girerek onun anısına dijital bir mum yakabilir, kendi yaşadıkları güzel anıları yazabilir veya bir taziye mesajı bırakabilirler. Yakılan her bir mum ve bırakılan her mesaj, dostunuzun sayfasında kalıcı olarak sergilenir. Böylece onun hayatımıza kattığı ışık, sevdiklerinizin desteğiyle sayfasında parlamaya devam eder.</p>\r\n<p>Amacımız, sosyal medyanın hızlı, karmaşık ve gelip geçici yapısından uzak; tamamen dostunuza saygı duruşu niteliğinde, sessiz ve huzurlu bir dijital köşe sunmaktır. Burası sadece size ait, reklamların veya ilgisiz içeriklerin olmadığı güvenli bir alandır.</p>\r\n<p>Biz, acıların paylaştıkça hafiflediğine ve bir can dostunun hatırasını hakkıyla yaşatmanın önemine inanıyoruz. Styever, size bu zorlu süreçte dostunuzun adını layık olduğu şekilde, tertemiz bir dijital albümde koruma imkânı sunar.</p>",
                            ContentEn = "<p>At Styever, we believe that one of the most meaningful ways to ease the grief and longing that follow the loss of a beloved companion is to keep their memories alive together with those who cared about them. Our <strong>Digital Candle Lighting</strong> and <strong>Memory Sharing</strong> features create a lasting memorial ritual that anyone visiting your companion's page can take part in.</p>\r\n<p><strong>How Does It Work?</strong> Visitors can enter your companion’s memorial page and light a digital candle in their honor, share cherished memories, or leave a message of condolence. Every candle lit and every message shared is permanently displayed on the memorial page. In this way, the light your companion brought into your life continues to shine through the support and remembrance of family and friends.</p>\r\n<p>Our goal is to provide a quiet and peaceful digital space, far removed from the fast-paced, cluttered, and temporary nature of social media. It is a place dedicated entirely to honoring your companion—a safe environment free from advertisements and unrelated content.</p>\r\n<p>We believe that grief becomes lighter when it is shared, and that every beloved companion deserves to be remembered with dignity and love. Styever gives you the opportunity to preserve your companion’s memory in a beautiful and lasting digital album, ensuring that their story continues to live on.</p>",
                            Header = "Dijital Mum Yakma ve Anı Paylaşımı Nasıl Çalışır?",
                            HeaderEn = "How Does Digital Candle Lighting and Memory Sharing Work?",
                            IsDeleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
