// <auto-generated />
using FAQManagement.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FAQManagement.Migrations
{
    [DbContext(typeof(FAQManagementContext))]
    [Migration("20260514091926_ıNİT")]
    partial class ıNİT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FAQManagement.Entity.FAQ", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "<p>Bir anı sayfası, kaybettiğiniz can dostunuzu sevgiyle hatırlamanın ve hatırasını onurlandırmanın dijital yoludur.</p><p>Fotoğraflar, videolar ve kalbinizden dökülen cümlelerle o güzel ruhun hikâyesini sonsuza dek yaşatmanıza imkan tanır.</p><p><strong>Styever anı sayfaları</strong>, sadece bir dijital günlük değil, aynı zamanda dostunuz adına yakılan her mumla sahipsiz hayvanların yaşam koşullarına katkı sağladığınız yaşayan bir sevgi defteridir.</p><p>Bu sayede dostunuzun hatırasını yaşatırken, dünyada somut bir iyilik izi bırakabilirsiniz.</p>",
                            ContentEn = "<p>A memorial page is a digital way to lovingly remember and honor the companion you have lost.</p><p>It allows you to keep the story of that beautiful soul alive forever through photos, videos, and words that come from your heart.</p><p><strong>Styever memorial pages</strong> are not simply digital journals; they are living books of love where every candle lit in your companion’s memory also contributes to improving the lives of stray animals.</p><p>In this way, while keeping your companion’s memory alive, you can also leave a meaningful mark of kindness in the world.</p>",
                            Header = "Bir \"Anı Sayfası\" tam olarak ne demek?",
                            HeaderEn = "What exactly is a \"Memorial Page\"?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2L,
                            Content = "<p>Hayır, Styever belirli bir ücretlendirme modeliyle çalışır.</p><p>Sevdiklerinizin anılarını uzun yıllar boyunca güvenle saklayabilmemiz için aşağıdaki operasyonel giderlerimiz bulunmaktadır:</p><ul><li>Yüksek kapasiteli veri depolama,</li><li>Fotoğraf ve video barındırma,</li><li>Teknik altyapı sürekliliği,</li><li>Sistem bakım maliyetleri.</li></ul><p>Dostlarınızın anı sayfalarının kesintisiz bir şekilde yayında kalmasını sağlamak ve sunduğumuz dijital deneyimi her geçen gün geliştirmek amacıyla bu sürdürülebilir ücretlendirme modelini uyguluyoruz.</p>",
                            ContentEn = "<p>No, Styever operates with a paid service model.</p><p>In order to securely preserve the memories of your loved ones for many years, we have operational costs such as:</p><ul><li>High-capacity data storage,</li><li>Photo and video hosting,</li><li>Technical infrastructure continuity,</li><li>Ongoing system maintenance.</li></ul><p>We apply this sustainable pricing model to ensure that your companions’ memorial pages remain continuously accessible and to keep improving the digital experience we provide every day.</p>",
                            Header = "Styever hizmetleri ücretsiz mi?",
                            HeaderEn = "Are Styever services free of charge?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3L,
                            Content = "<p>Anı sayfanız, bağlantıya sahip olan herkes tarafından ziyaret edilebilir.</p><p>Sayfanızın linkini ailenizle, arkadaşlarınızla veya dostunuzu tanıyan herkesle paylaşarak bu özel hatıranın büyümesine vesile olabilirsiniz.</p><p>Paylaştığınız link sayesinde sevdikleriniz de sayfayı ziyaret edebilir, anıları okuyabilir ve dijital bir mum yakarak bu sevgiye ortak olabilir.</p>",
                            ContentEn = "<p>Your memorial page can be visited by anyone who has the link.</p><p>By sharing your page with family members, friends, or anyone who knew your beloved companion, you can help this special memory continue to grow.</p><p>Through the shared link, your loved ones can visit the page, read the memories, and join in this act of love by lighting a digital candle.</p>",
                            Header = "Anma sayfamı kimler görebilir?",
                            HeaderEn = "Who can see my memorial page?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4L,
                            Content = "<p>Evet, dilediğiniz an iptal edebilirsiniz.</p><p><strong>Styever, kullanıcılarına herhangi bir taahhüt veya zorunluluk sunmaz.</strong></p><p>Kontrol tamamen sizdedir; dilediğiniz zaman hesap ayarlarınız üzerinden aboneliğinizi sonlandırabilirsiniz.</p><p>İptal işleminizden sonra, o ay için geçerli olan haklarınız dönem sonuna kadar devam eder ve bir sonraki dönem için yeni bir ödeme alınmaz.</p>",
                            ContentEn = "<p>Yes, you may cancel at any time.</p><p><strong>Styever does not impose any commitments or obligations on its users.</strong></p><p>You remain fully in control and can end your subscription whenever you wish through your account settings.</p><p>After cancellation, your current membership benefits will remain active until the end of the billing period, and no new payment will be charged for the following period.</p>",
                            Header = "Aboneliği istediğim zaman iptal edebilir miyim?",
                            HeaderEn = "Can I cancel my subscription at any time?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5L,
                            Content = "<p>Hayır, anı sayfanız yayında kalmaya devam eder.</p><p>Üyeliğiniz sona erdiğinde yalnızca aşağıdaki güncelleme yetkileri kısıtlanır:</p><ul><li>Yeni fotoğraf ekleme,</li><li>Mevcut metinleri düzenleme,</li><li>Sayfa içeriğini güncelleme.</li></ul><p>Ancak dostunuzun hatırası dijital dünyadaki yerini korur.</p><p>Eğer sayfanın tamamen kaldırılmasını isterseniz, kayıtlı e-posta adresiniz ve sayfa isminizle birlikte <strong>info@styever.com</strong> üzerinden bize ulaşabilirsiniz.</p><p>Talebiniz doğrultusunda ilgili sayfa en geç <strong>48 saat</strong> içerisinde sistemimizden tamamen silinecektir.</p>",
                            ContentEn = "<p>No, your memorial page will remain published and accessible.</p><p>When your membership ends, only update permissions will be restricted, such as:</p><ul><li>Adding new photos,</li><li>Editing existing texts,</li><li>Updating page content.</li></ul><p>However, your companion’s memory will continue to have its place in the digital world.</p><p>If you would like the page to be completely removed, you may contact us at <strong>info@styever.com</strong> using your registered email address and the name of the memorial page.</p><p>In line with your request, the relevant page will be permanently deleted from our system within <strong>48 hours</strong> at the latest.</p>",
                            Header = "Üyeliğimi iptal edersem anı sayfam silinir mi?",
                            HeaderEn = "Will my memorial page be deleted if I cancel my membership?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6L,
                            Content = "<p>Styever, her ihtiyaca ve her anıya uygun üç farklı abonelik seçeneği sunar:</p><ul><li><strong>Anı Paketi:</strong> Sade ve anlamlı bir hatıra bırakmak isteyenler için tasarlandı. Tek bir özel fotoğraf ve biyografi alanı ile dostunuzun temel bilgilerini ve hatırasını dijital dünyada ölümsüzleştirebilirsiniz.</li><li><strong>Hatıra Paketi:</strong> Daha derin bir hikâye anlatmak isteyenler için idealdir. Birden fazla fotoğraf, video galerisi, kapsamlı bir biyografi bölümü ve YouTube içerikleriyle dostunuzun yaşam yolculuğunu tüm detaylarıyla paylaşmanıza imkan tanır.</li><li><strong>Sonsuz Paket:</strong> Birden fazla dostunu aynı anda anmak isteyen büyük aileler için en kapsamlı seçeneğimizdir. Bu paketle dört ayrı anı sayfası oluşturabilir; her dostunuz için bağımsız galeriler, hikâyeler ve dijital alanlar tanımlayabilirsiniz.</li></ul>",
                            ContentEn = "<p>Styever offers three different subscription options designed to suit every need and every memory:</p><ul><li><strong>Memory Package:</strong> Designed for those who wish to leave a simple yet meaningful tribute. With a single special photo and a biography section, you can immortalize your companion’s essential information and memory in the digital world.</li><li><strong>Tribute Package:</strong> Ideal for those who want to tell a deeper story. With multiple photos, a video gallery, an extended biography section, and YouTube content integration, you can share your companion’s life journey in full detail.</li><li><strong>Eternal Package:</strong> Our most comprehensive option for large families who wish to honor more than one companion at the same time. With this package, you can create four separate memorial pages and define independent galleries, stories, and digital spaces for each of your beloved companions.</li></ul>",
                            Header = "Planlar arasındaki fark ne?",
                            HeaderEn = "What's the difference between the plans?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7L,
                            Content = "<p>Elbette.</p><p>Aradan ne kadar zaman geçmiş olursa olsun, <strong>sevgi eskimez</strong>.</p><p>Hazır hissettiğiniz gün Styever’da sayfayı açabilir, onun izini kalıcılaştırabilirsiniz.</p>",
                            ContentEn = "<p>Of course.</p><p>No matter how much time passes, <strong>love never fades</strong>.</p><p>Whenever you feel ready, you can open a new page on Styever and immortalize your companion’s memory.</p>",
                            Header = "Yıllar önce kaybettiğim pet için de anma oluşturabilir miyim?",
                            HeaderEn = "Can I also create a memorial for my pet that I lost years ago?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8L,
                            Content = "<p>Styever’da ödemeler tek seferliktir.</p><p>Anma sayfasını oluşturduğunuzda sayfa size ait olur.</p><p>Ayrıca <strong>12 ay boyunca</strong> sayfanızı özgürce düzenleyebilir, yeni fotoğraflar ekleyebilir ve dilediğinizde yeniden şekillendirebilirsiniz.</p><p>Bu sürenin sonunda düzenleme hakkı sona erer; ancak anı sayfanız yayında kalmaya devam eder.</p><p>Sayfanızı dilediğiniz gibi düzenlemeye devam etmek isterseniz aboneliğinizi yenileyebilirsiniz.</p>",
                            ContentEn = "<p>At Styever, payments are one-time only.</p><p>Once you create your memorial page, it becomes yours.</p><p>You can also freely edit your page, add new photos, and reshape it as you wish for <strong>12 months</strong>.</p><p>At the end of this period, your editing rights expire; however, your memorial page remains live.</p><p>If you want to continue editing your page as you wish, you can renew your subscription.</p>",
                            Header = "Ödeme modeli nasıl işliyor?",
                            HeaderEn = "How does the payment model work?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9L,
                            Content = "<p>Evet.</p><p><strong>12 aylık düzenleme süresi boyunca</strong> sayfayı dilediğiniz kadar yenileyebilir, anılar ekleyebilir ve anlatımınızı derinleştirebilirsiniz.</p>",
                            ContentEn = "<p>Yes.</p><p>During the <strong>12-month editing period</strong>, you can refresh the page as much as you want, add memories, and deepen your narrative.</p>",
                            Header = "Daha sonra düzenleme yapabilir miyim?",
                            HeaderEn = "Can I make changes later?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10L,
                            Content = "<p>Evet.</p><p>Anı ya da Hatıra Paketlerinden biri ile başladığınızda, daha sonra planınızı yükseltip daha kapsamlı bir anı alanına geçebilirsiniz.</p>",
                            ContentEn = "<p>Yes.</p><p>When you start with either a Memory or Tribute Package, you can later upgrade your plan to a more comprehensive memorial package.</p>",
                            Header = "Planımı sonradan yükseltebilir miyim?",
                            HeaderEn = "Can I upgrade my plan later?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11L,
                            Content = "<p>Evet — özellikle <strong>Sonsuz Paket</strong> bunun için tasarlanmıştır.</p><p>Aynı hesapla dört farklı dostunuz için dört ayrı anma sayfası oluşturabilir, her birine özel bir hikâye alanı ayırabilirsiniz.</p>",
                            ContentEn = "<p>Yes — the <strong>Eternal Package</strong> is specifically designed for this.</p><p>With the same account, you can create four separate memorial pages for four different companions and dedicate a unique story space to each of them.</p>",
                            Header = "Birden fazla can dostum için anma sayfası açabilir miyim?",
                            HeaderEn = "Can I create memorial pages for more than one best friend?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12L,
                            Content = "<p>Styever’a üye olduğunuzda, platformun desteklediği projeler veya kuruluşlar arasından dilediğinizi seçebilirsiniz.</p><p>Seçtiğiniz bu projeye, ödediğiniz abonelik ücretinin net tutarı üzerinden <strong>%20 sosyal sorumluluk payı</strong> sizin adınıza tanımlanır ve ilgili kuruma iletilir.</p><p>Dostunuzun anı sayfasında her dijital mum yakıldığında, bu işlem bedelinin <strong>%80’i</strong> yine seçtiğiniz projeye veya ilgili kuruluşa ulaştırılır.</p><ul><li>Adınıza sosyal sorumluluk sertifikası oluşturulur.</li><li>Sertifika e-posta yoluyla size ulaştırılır.</li><li>Destekler ilgili proje veya kuruluşa şeffaf biçimde aktarılır.</li></ul><p>Styever, bu süreçte elde edilen toplam gelirin bir kısmını platformun devamlılığını sağlamak, anı sayfalarını güvenli bir şekilde barındırmak ve teknik altyapıyı sürdürebilmek amacıyla kullanır.</p><p>Böylece hem sahipsiz dostlarımıza sağlanan destekler şeffaf bir biçimde yerine ulaşır hem de sevdiklerinizin hatıralarını yaşatan bu dijital alan kesintisiz bir şekilde varlığını sürdürür.</p>",
                            ContentEn = "<p>When you become a member of Styever, you may choose any of the projects or organizations supported by the platform.</p><p>For the project you select, <strong>20% of the net amount</strong> of your subscription payment is allocated as a social responsibility contribution on your behalf and transferred to the relevant organization.</p><p>Each time a digital candle is lit on your companion’s memorial page, <strong>80% of the transaction amount</strong> is also directed to the project or organization you selected.</p><ul><li>A social responsibility certificate is issued in your name.</li><li>The certificate is delivered to you via email.</li><li>Support is transferred transparently to the relevant project or organization.</li></ul><p>Styever uses a portion of the total revenue generated during this process to ensure the continuity of the platform, securely host memorial pages, and maintain the technical infrastructure.</p><p>In this way, support provided to stray companions is delivered transparently, while this digital space that keeps your loved ones’ memories alive continues to exist without interruption.</p>",
                            Header = "Sosyal sorumluluk süreci nasıl işliyor?",
                            HeaderEn = "How Does the Social Responsibility Process Work?",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 13L,
                            Content = "<p>Styever olarak, kaybettiklerimizi sevgiyle anarken bugün yaşayan dostlarımızı korumayı bir görev kabul ediyoruz.</p><p>Platformumuzda gerçekleştirilen her <strong>“Mum Yakma”</strong> işlemi, yalnızca dijital bir anma ritüeli değil, aynı zamanda sahipsiz hayvanların yaşam koşullarını iyileştiren somut bir destek fırsatıdır.</p><p><strong>Süreç Nasıl İşler?</strong></p><p>Ziyaretçiler, kaybettikleri dostlarının anısına dijital bir mum yakarak onları sevgiyle anabilir ve hatıralarını tazeleyebilir.</p><p>Bu işlem sırasında elde edilen dijital hizmet gelirinin büyük bir kısmı, sosyal sorumluluk vizyonumuz kapsamında sahipsiz hayvanların mama, barınma ve tedavi ihtiyaçlarını karşılayan kuruluşlara ve projelere kaynak olarak ulaştırılır.</p><p><strong>Amacımız</strong></p><p>Dijital anıları toplumsal bir faydaya dönüştürerek sürdürülebilir bir dayanışma modeli oluşturmaktır.</p><ul><li>Her bir ışık, bir anıyı onurlandırır.</li><li>Her dijital mum, bir canın hayatında fark yaratan gerçek bir desteğe vesile olur.</li><li>Her paylaşılan anı, iyiliğe dönüşen bir bağ kurar.</li></ul><p>Biz, hatırlamanın iyileştirdiğine ve paylaşılan her anının bir başka cana nefes olabileceğine inanıyoruz.</p><p>Styever; bir dijital anma deneyimi sunarken, kullanıcılarını hayvan refahını destekleyen sosyal sorumluluk projelerinin bir parçası haline getirerek, sevgiyi ve hatıraları yaşayan bir iyilik hareketine dönüştürür.</p>",
                            ContentEn = "<p>As Styever, while remembering those we have lost with love, we also consider protecting the companions who are still with us today as an important responsibility.</p><p>Every <strong>“Light a Candle”</strong> interaction on our platform is not only a digital memorial ritual, but also a meaningful opportunity to support and improve the living conditions of stray animals.</p><p><strong>How Does the Process Work?</strong></p><p>Visitors can light a digital candle in memory of their beloved companions, honoring them with love and keeping their memories alive.</p><p>A significant portion of the digital service revenue generated through this interaction is allocated, within the scope of our social responsibility vision, to organizations and projects that support the food, shelter, and medical treatment needs of stray animals.</p><p><strong>Our Purpose</strong></p><p>Our goal is to create a sustainable model of solidarity by transforming digital memories into social benefit.</p><ul><li>Every light honors a cherished memory.</li><li>Every digital candle becomes real support that makes a difference in the life of an animal in need.</li><li>Every shared memory creates a bond that turns into kindness.</li></ul><p>We believe that remembering has the power to heal, and that every shared memory can become a source of hope for another living soul.</p><p>While offering a digital memorial experience, Styever transforms love and memories into a living movement of kindness by making its users part of social responsibility projects that support animal welfare.</p>",
                            Header = "Anıları İyiliğe Dönüştürün",
                            HeaderEn = "Transform Memories into Kindness",
                            IsDeleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
