using Microsoft.EntityFrameworkCore;
using UserManagement.Entity;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace UserManagement.DbContexts
{
    public class UserManagementContext : DbContext
    {
        public UserManagementContext(DbContextOptions<UserManagementContext> options) : base(options)
        {
        }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RolePermission> RolePermissions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<UserPermission> UserPermissions { get; set; }
        public DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public DbSet<UserAddress> UserAddresses { get; set; }
        public DbSet<UserPayment> UserPayments { get; set; }
        public DbSet<UserVoucher> UserVouchers { get; set; }
        public DbSet<ShopierPayment> ShopierPayments { get; set; }
        public DbSet<UserAgreementAcceptance> UserAgreementAcceptances { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ShopierPayment>().HasIndex(x => x.Reference).IsUnique();
            modelBuilder.Entity<ShopierPayment>().HasIndex(x => x.ShopierOrderId).IsUnique();
            modelBuilder.Entity<UserAgreementAcceptance>().HasIndex(x => new { x.UserId, x.AcceptedDate });

            modelBuilder.Entity<Permission>().HasData(
                new Permission { Id = 1, Name = "Yetki Ekranı Sayfalama Yetkisi", Code = "PermissionScene.Paging.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 2, Name = "Yetki Ekranı Kayıt Yetkisi", Code = "PermissionScene.Save.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 3, Name = "Yetki Ekranı Güncelleme Yetkisi", Code = "PermissionScene.Edit.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 4, Name = "Yetki Ekranı Silme Yetkisi", Code = "PermissionScene.Delete.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 5, Name = "Yetki Ekranı Listeleme Yetkisi", Code = "PermissionScene.List.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 6, Name = "Yetki Ekranı Yetki Alma Yetkisi", Code = "PermissionScene.GetById.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 7, Name = "Rol Ekranı Sayfalama Yetkisi", Code = "RoleScene.Paging.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 8, Name = "Rol Ekranı Kayıt Yetkisi", Code = "RoleScene.Save.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 9, Name = "Rol Ekranı Güncelleme Yetkisi", Code = "RoleScene.Edit.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 10, Name = "Rol Ekranı Silme Yetkisi", Code = "RoleScene.Delete.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 11, Name = "Rol Ekranı Listeleme Yetkisi", Code = "RoleScene.List.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 12, Name = "Rol Ekranı Rol Alma Yetkisi", Code = "RoleScene.GetById.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 13, Name = "Kullanıcı Ekranı Sayfalama Yetkisi", Code = "UserScene.Paging.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 14, Name = "Kullanıcı Ekranı Kayıt Yetkisi", Code = "UserScene.Save.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 15, Name = "Kullanıcı Ekranı Güncelleme Yetkisi", Code = "UserScene.Edit.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 16, Name = "Kullanıcı Ekranı Silme Yetkisi", Code = "UserScene.Delete.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 17, Name = "Kullanıcı Ekranı Listeleme Yetkisi", Code = "UserScene.List.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 18, Name = "Profil Ekranı Şifre Değiştirme Yetkisi", Code = "ProfileScene.ChangePw.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 19, Name = "Profil Ekranı Güncelleme Yetkisi", Code = "ProfileScene.Edit.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 20, Name = "Profil Ekranı Avatar Güncelleme Yetkisi", Code = "ProfileScene.AvatarEdit.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 21, Name = "Profil Ekranı Adres Listeleme Yetkisi", Code = "ProfileScene.ListAddress.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 22, Name = "Profil Ekranı Adres Kayıt Yetkisi", Code = "ProfileScene.SaveAddress.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 23, Name = "Profil Ekranı Adres Güncelleme Yetkisi", Code = "ProfileScene.EditAddress.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 24, Name = "Profil Ekranı Adres Silme Yetkisi", Code = "ProfileScene.DeletAddress.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 25, Name = "Profil Ekranı Adres Alma Yetkisi", Code = "ProfileScene.GetAddressById.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 26, Name = "Ödeme Ekranı Üyelik Ödeme Yetkisi", Code = "PaymentScene.MembershipPayment.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 27, Name = "Ödeme Ekranı Üyelik Satın Alma Yetkisi", Code = "PaymentScene.BuyMembership.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 28, Name = "Dosya Yükleme Yetkisi", Code = "File.Save.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 29, Name = "Dosya Silme Yetkisi", Code = "File.Delete.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 30, Name = "Hatıra Ekranı Kayıt Yetkisi", Code = "MemoryScene.Save.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 31, Name = "Hatıra Ekranı Güncelleme Yetkisi", Code = "MemoryScene.Edit.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 32, Name = "Hatıra Ekranı Sayaç Yetkisi", Code = "MemoryScene.Count.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 33, Name = "Hatıra Ekranı Dosya Güncelleme Yetkisi", Code = "MemoryScene.FileUpdate.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 34, Name = "Hatıra Ekranı Dosya Ekleme Yetkisi", Code = "MemoryScene.FileAdd.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 35, Name = "Hatıra Ekranı Dosya Silme Yetkisi", Code = "MemoryScene.FileDelete.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 36, Name = "Hatıra Ekranı Mum Yakma Yetkisi", Code = "MemoryScene.LightCandle.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 37, Name = "Hatıra Ekranı Mum Yakma Güncelleme Yetkisi", Code = "MemoryScene.UpdateCandle.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 38, Name = "Hatıra Ekranı Yorum Yapma Yetkisi", Code = "MemoryScene.AddComment.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 39, Name = "Hatıra Ekranı Yorum Silme Yetkisi", Code = "MemoryScene.DeleteComment.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 40, Name = "Hatıra Ekranı Beğeni Yetkisi", Code = "MemoryScene.Like.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 41, Name = "Hatıra Ekranı Beğeni Silme Yetkisi", Code = "MemoryScene.Dislike.Permission", IsDeleted = false, IsSystemData = true },
                new Permission { Id = 42, Name = "Hatıra Ekranı Yorum Onaylama Yetkisi", Code = "MemoryScene.ApproveComment.Permission", IsDeleted = false, IsSystemData = true }

             );


            modelBuilder.Entity<Role>().HasData(
                new Role { Id = 1, Name = "SuperAdmin", IsDeleted = false, IsSystemData = true },
                new Role { Id = 2, Name = "Origin", IsDeleted = false, IsSystemData = true },
                new Role { Id = 3, Name = "Heart", IsDeleted = false, IsSystemData = true },
                new Role { Id = 4, Name = "Family", IsDeleted = false, IsSystemData = true }
            );

            modelBuilder.Entity<RolePermission>().HasData(
                //SuperAdmin Role Perms
                new RolePermission { Id = 1, RoleId = 1, PermissionId = 1, IsDeleted = false },
                new RolePermission { Id = 2, RoleId = 1, PermissionId = 2, IsDeleted = false },
                new RolePermission { Id = 3, RoleId = 1, PermissionId = 3, IsDeleted = false },
                new RolePermission { Id = 4, RoleId = 1, PermissionId = 4, IsDeleted = false },
                new RolePermission { Id = 5, RoleId = 1, PermissionId = 5, IsDeleted = false },
                new RolePermission { Id = 6, RoleId = 1, PermissionId = 6, IsDeleted = false },
                new RolePermission { Id = 7, RoleId = 1, PermissionId = 7, IsDeleted = false },
                new RolePermission { Id = 8, RoleId = 1, PermissionId = 8, IsDeleted = false },
                new RolePermission { Id = 9, RoleId = 1, PermissionId = 9, IsDeleted = false },
                new RolePermission { Id = 10, RoleId = 1, PermissionId = 10, IsDeleted = false },
                new RolePermission { Id = 11, RoleId = 1, PermissionId = 11, IsDeleted = false },
                new RolePermission { Id = 12, RoleId = 1, PermissionId = 12, IsDeleted = false },
                new RolePermission { Id = 13, RoleId = 1, PermissionId = 13, IsDeleted = false },
                new RolePermission { Id = 14, RoleId = 1, PermissionId = 14, IsDeleted = false },
                new RolePermission { Id = 15, RoleId = 1, PermissionId = 15, IsDeleted = false },
                new RolePermission { Id = 16, RoleId = 1, PermissionId = 16, IsDeleted = false },
                new RolePermission { Id = 17, RoleId = 1, PermissionId = 17, IsDeleted = false },
                new RolePermission { Id = 18, RoleId = 1, PermissionId = 18, IsDeleted = false },
                new RolePermission { Id = 19, RoleId = 1, PermissionId = 19, IsDeleted = false },
                new RolePermission { Id = 20, RoleId = 1, PermissionId = 20, IsDeleted = false },
                new RolePermission { Id = 21, RoleId = 1, PermissionId = 21, IsDeleted = false },
                new RolePermission { Id = 22, RoleId = 1, PermissionId = 22, IsDeleted = false },
                new RolePermission { Id = 23, RoleId = 1, PermissionId = 23, IsDeleted = false },
                new RolePermission { Id = 24, RoleId = 1, PermissionId = 24, IsDeleted = false },
                new RolePermission { Id = 25, RoleId = 1, PermissionId = 25, IsDeleted = false },
                new RolePermission { Id = 26, RoleId = 1, PermissionId = 26, IsDeleted = false },
                new RolePermission { Id = 27, RoleId = 1, PermissionId = 27, IsDeleted = false },
                new RolePermission { Id = 28, RoleId = 1, PermissionId = 28, IsDeleted = false },
                new RolePermission { Id = 29, RoleId = 1, PermissionId = 29, IsDeleted = false },
                new RolePermission { Id = 30, RoleId = 1, PermissionId = 30, IsDeleted = false },
                new RolePermission { Id = 31, RoleId = 1, PermissionId = 31, IsDeleted = false },
                new RolePermission { Id = 32, RoleId = 1, PermissionId = 32, IsDeleted = false },
                new RolePermission { Id = 33, RoleId = 1, PermissionId = 33, IsDeleted = false },
                new RolePermission { Id = 34, RoleId = 1, PermissionId = 34, IsDeleted = false },
                new RolePermission { Id = 35, RoleId = 1, PermissionId = 35, IsDeleted = false },
                new RolePermission { Id = 36, RoleId = 1, PermissionId = 36, IsDeleted = false },
                new RolePermission { Id = 37, RoleId = 1, PermissionId = 37, IsDeleted = false },
                new RolePermission { Id = 38, RoleId = 1, PermissionId = 38, IsDeleted = false },
                new RolePermission { Id = 39, RoleId = 1, PermissionId = 39, IsDeleted = false },
                new RolePermission { Id = 40, RoleId = 1, PermissionId = 40, IsDeleted = false },
                new RolePermission { Id = 41, RoleId = 1, PermissionId = 41, IsDeleted = false },
                //Memory Role Perms
                new RolePermission { Id = 42, RoleId = 2, PermissionId = 1, IsDeleted = false },
                new RolePermission { Id = 43, RoleId = 2, PermissionId = 2, IsDeleted = false },
                new RolePermission { Id = 44, RoleId = 2, PermissionId = 3, IsDeleted = false },
                new RolePermission { Id = 45, RoleId = 2, PermissionId = 4, IsDeleted = false },
                new RolePermission { Id = 46, RoleId = 2, PermissionId = 5, IsDeleted = false },
                new RolePermission { Id = 47, RoleId = 2, PermissionId = 6, IsDeleted = false },
                new RolePermission { Id = 48, RoleId = 2, PermissionId = 7, IsDeleted = false },
                new RolePermission { Id = 49, RoleId = 2, PermissionId = 8, IsDeleted = false },
                new RolePermission { Id = 50, RoleId = 2, PermissionId = 9, IsDeleted = false },
                new RolePermission { Id = 51, RoleId = 2, PermissionId = 10, IsDeleted = false },
                new RolePermission { Id = 52, RoleId = 2, PermissionId = 11, IsDeleted = false },
                new RolePermission { Id = 53, RoleId = 2, PermissionId = 12, IsDeleted = false },
                new RolePermission { Id = 54, RoleId = 2, PermissionId = 13, IsDeleted = false },
                new RolePermission { Id = 55, RoleId = 2, PermissionId = 14, IsDeleted = false },
                new RolePermission { Id = 56, RoleId = 2, PermissionId = 15, IsDeleted = false },
                new RolePermission { Id = 57, RoleId = 2, PermissionId = 16, IsDeleted = false },
                new RolePermission { Id = 58, RoleId = 2, PermissionId = 17, IsDeleted = false },
                new RolePermission { Id = 59, RoleId = 2, PermissionId = 18, IsDeleted = false },
                new RolePermission { Id = 60, RoleId = 2, PermissionId = 19, IsDeleted = false },
                new RolePermission { Id = 61, RoleId = 2, PermissionId = 20, IsDeleted = false },
                new RolePermission { Id = 62, RoleId = 2, PermissionId = 21, IsDeleted = false },
                new RolePermission { Id = 63, RoleId = 2, PermissionId = 22, IsDeleted = false },
                new RolePermission { Id = 64, RoleId = 2, PermissionId = 23, IsDeleted = false },
                new RolePermission { Id = 65, RoleId = 2, PermissionId = 24, IsDeleted = false },
                new RolePermission { Id = 66, RoleId = 2, PermissionId = 25, IsDeleted = false },
                new RolePermission { Id = 67, RoleId = 2, PermissionId = 26, IsDeleted = false },
                new RolePermission { Id = 68, RoleId = 2, PermissionId = 27, IsDeleted = false },
                new RolePermission { Id = 69, RoleId = 2, PermissionId = 28, IsDeleted = false },
                new RolePermission { Id = 70, RoleId = 2, PermissionId = 29, IsDeleted = false },
                new RolePermission { Id = 71, RoleId = 2, PermissionId = 30, IsDeleted = false },
                new RolePermission { Id = 72, RoleId = 2, PermissionId = 31, IsDeleted = false },
                new RolePermission { Id = 73, RoleId = 2, PermissionId = 32, IsDeleted = false },
                new RolePermission { Id = 74, RoleId = 2, PermissionId = 33, IsDeleted = false },
                new RolePermission { Id = 75, RoleId = 2, PermissionId = 34, IsDeleted = false },
                new RolePermission { Id = 76, RoleId = 2, PermissionId = 35, IsDeleted = false },
                new RolePermission { Id = 77, RoleId = 2, PermissionId = 36, IsDeleted = false },
                new RolePermission { Id = 78, RoleId = 2, PermissionId = 37, IsDeleted = false },
                new RolePermission { Id = 79, RoleId = 2, PermissionId = 38, IsDeleted = false },
                new RolePermission { Id = 80, RoleId = 2, PermissionId = 39, IsDeleted = false },
                new RolePermission { Id = 81, RoleId = 2, PermissionId = 40, IsDeleted = false },
                new RolePermission { Id = 82, RoleId = 2, PermissionId = 41, IsDeleted = false },
                //Tribute Role Perms
                new RolePermission { Id = 83, RoleId = 3, PermissionId = 1, IsDeleted = false },
                new RolePermission { Id = 84, RoleId = 3, PermissionId = 2, IsDeleted = false },
                new RolePermission { Id = 85, RoleId = 3, PermissionId = 3, IsDeleted = false },
                new RolePermission { Id = 86, RoleId = 3, PermissionId = 4, IsDeleted = false },
                new RolePermission { Id = 87, RoleId = 3, PermissionId = 5, IsDeleted = false },
                new RolePermission { Id = 88, RoleId = 3, PermissionId = 6, IsDeleted = false },
                new RolePermission { Id = 89, RoleId = 3, PermissionId = 7, IsDeleted = false },
                new RolePermission { Id = 90, RoleId = 3, PermissionId = 8, IsDeleted = false },
                new RolePermission { Id = 91, RoleId = 3, PermissionId = 9, IsDeleted = false },
                new RolePermission { Id = 92, RoleId = 3, PermissionId = 10, IsDeleted = false },
                new RolePermission { Id = 93, RoleId = 3, PermissionId = 11, IsDeleted = false },
                new RolePermission { Id = 94, RoleId = 3, PermissionId = 12, IsDeleted = false },
                new RolePermission { Id = 95, RoleId = 3, PermissionId = 13, IsDeleted = false },
                new RolePermission { Id = 96, RoleId = 3, PermissionId = 14, IsDeleted = false },
                new RolePermission { Id = 97, RoleId = 3, PermissionId = 15, IsDeleted = false },
                new RolePermission { Id = 98, RoleId = 3, PermissionId = 16, IsDeleted = false },
                new RolePermission { Id = 99, RoleId = 3, PermissionId = 17, IsDeleted = false },
                new RolePermission { Id = 100, RoleId = 3, PermissionId = 18, IsDeleted = false },
                new RolePermission { Id = 101, RoleId = 3, PermissionId = 19, IsDeleted = false },
                new RolePermission { Id = 102, RoleId = 3, PermissionId = 20, IsDeleted = false },
                new RolePermission { Id = 103, RoleId = 3, PermissionId = 21, IsDeleted = false },
                new RolePermission { Id = 104, RoleId = 3, PermissionId = 22, IsDeleted = false },
                new RolePermission { Id = 105, RoleId = 3, PermissionId = 23, IsDeleted = false },
                new RolePermission { Id = 106, RoleId = 3, PermissionId = 24, IsDeleted = false },
                new RolePermission { Id = 107, RoleId = 3, PermissionId = 25, IsDeleted = false },
                new RolePermission { Id = 108, RoleId = 3, PermissionId = 26, IsDeleted = false },
                new RolePermission { Id = 109, RoleId = 3, PermissionId = 27, IsDeleted = false },
                new RolePermission { Id = 110, RoleId = 3, PermissionId = 28, IsDeleted = false },
                new RolePermission { Id = 111, RoleId = 3, PermissionId = 29, IsDeleted = false },
                new RolePermission { Id = 112, RoleId = 3, PermissionId = 30, IsDeleted = false },
                new RolePermission { Id = 113, RoleId = 3, PermissionId = 31, IsDeleted = false },
                new RolePermission { Id = 114, RoleId = 3, PermissionId = 32, IsDeleted = false },
                new RolePermission { Id = 115, RoleId = 3, PermissionId = 33, IsDeleted = false },
                new RolePermission { Id = 116, RoleId = 3, PermissionId = 34, IsDeleted = false },
                new RolePermission { Id = 117, RoleId = 3, PermissionId = 35, IsDeleted = false },
                new RolePermission { Id = 118, RoleId = 3, PermissionId = 36, IsDeleted = false },
                new RolePermission { Id = 119, RoleId = 3, PermissionId = 37, IsDeleted = false },
                new RolePermission { Id = 120, RoleId = 3, PermissionId = 38, IsDeleted = false },
                new RolePermission { Id = 121, RoleId = 3, PermissionId = 39, IsDeleted = false },
                new RolePermission { Id = 122, RoleId = 3, PermissionId = 40, IsDeleted = false },
                new RolePermission { Id = 123, RoleId = 3, PermissionId = 41, IsDeleted = false },
                //Eternal Role Perms
                new RolePermission { Id = 124, RoleId = 4, PermissionId = 1, IsDeleted = false },
                new RolePermission { Id = 125, RoleId = 4, PermissionId = 2, IsDeleted = false },
                new RolePermission { Id = 126, RoleId = 4, PermissionId = 3, IsDeleted = false },
                new RolePermission { Id = 127, RoleId = 4, PermissionId = 4, IsDeleted = false },
                new RolePermission { Id = 128, RoleId = 4, PermissionId = 5, IsDeleted = false },
                new RolePermission { Id = 129, RoleId = 4, PermissionId = 6, IsDeleted = false },
                new RolePermission { Id = 130, RoleId = 4, PermissionId = 7, IsDeleted = false },
                new RolePermission { Id = 131, RoleId = 4, PermissionId = 8, IsDeleted = false },
                new RolePermission { Id = 132, RoleId = 4, PermissionId = 9, IsDeleted = false },
                new RolePermission { Id = 133, RoleId = 4, PermissionId = 10, IsDeleted = false },
                new RolePermission { Id = 134, RoleId = 4, PermissionId = 11, IsDeleted = false },
                new RolePermission { Id = 135, RoleId = 4, PermissionId = 12, IsDeleted = false },
                new RolePermission { Id = 136, RoleId = 4, PermissionId = 13, IsDeleted = false },
                new RolePermission { Id = 137, RoleId = 4, PermissionId = 14, IsDeleted = false },
                new RolePermission { Id = 138, RoleId = 4, PermissionId = 15, IsDeleted = false },
                new RolePermission { Id = 139, RoleId = 4, PermissionId = 16, IsDeleted = false },
                new RolePermission { Id = 140, RoleId = 4, PermissionId = 17, IsDeleted = false },
                new RolePermission { Id = 141, RoleId = 4, PermissionId = 18, IsDeleted = false },
                new RolePermission { Id = 142, RoleId = 4, PermissionId = 19, IsDeleted = false },
                new RolePermission { Id = 143, RoleId = 4, PermissionId = 20, IsDeleted = false },
                new RolePermission { Id = 144, RoleId = 4, PermissionId = 21, IsDeleted = false },
                new RolePermission { Id = 145, RoleId = 4, PermissionId = 22, IsDeleted = false },
                new RolePermission { Id = 146, RoleId = 4, PermissionId = 23, IsDeleted = false },
                new RolePermission { Id = 147, RoleId = 4, PermissionId = 24, IsDeleted = false },
                new RolePermission { Id = 148, RoleId = 4, PermissionId = 25, IsDeleted = false },
                new RolePermission { Id = 149, RoleId = 4, PermissionId = 26, IsDeleted = false },
                new RolePermission { Id = 150, RoleId = 4, PermissionId = 27, IsDeleted = false },
                new RolePermission { Id = 151, RoleId = 4, PermissionId = 28, IsDeleted = false },
                new RolePermission { Id = 152, RoleId = 4, PermissionId = 29, IsDeleted = false },
                new RolePermission { Id = 153, RoleId = 4, PermissionId = 30, IsDeleted = false },
                new RolePermission { Id = 154, RoleId = 4, PermissionId = 31, IsDeleted = false },
                new RolePermission { Id = 155, RoleId = 4, PermissionId = 32, IsDeleted = false },
                new RolePermission { Id = 156, RoleId = 4, PermissionId = 33, IsDeleted = false },
                new RolePermission { Id = 157, RoleId = 4, PermissionId = 34, IsDeleted = false },
                new RolePermission { Id = 158, RoleId = 4, PermissionId = 35, IsDeleted = false },
                new RolePermission { Id = 159, RoleId = 4, PermissionId = 36, IsDeleted = false },
                new RolePermission { Id = 160, RoleId = 4, PermissionId = 37, IsDeleted = false },
                new RolePermission { Id = 161, RoleId = 4, PermissionId = 38, IsDeleted = false },
                new RolePermission { Id = 162, RoleId = 4, PermissionId = 39, IsDeleted = false },
                new RolePermission { Id = 163, RoleId = 4, PermissionId = 40, IsDeleted = false },
                new RolePermission { Id = 164, RoleId = 4, PermissionId = 41, IsDeleted = false },
                new RolePermission { Id = 165, RoleId = 1, PermissionId = 42, IsDeleted = false },
                new RolePermission { Id = 166, RoleId = 2, PermissionId = 42, IsDeleted = false },
                new RolePermission { Id = 167, RoleId = 3, PermissionId = 42, IsDeleted = false },
                new RolePermission { Id = 168, RoleId = 4, PermissionId = 42, IsDeleted = false }

            );

            modelBuilder.Entity<User>().HasData(
                new User { 
                    Id = 1, 
                    Name = "SuperAdmin",
                    Surname = "SuperAdmin",
                    Email = "super@test.com",
                    Password = "DBD9DCE9DB51E56E1468B18F44233EB1FF625ADCECAAE2D7E9776BC714AF69D2A360B57CDB7C4E098C6225543BF83C50DAEC23A8DAADF9212BADF6F26760911C", 
                    Phone = "+905077352772",
                    Username = "superadmin",
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow,
                    TrialExpirationDate = DateTime.UtcNow.AddDays(7),
                    ExpirationDate = DateTime.UtcNow.AddYears(1),
                    Salt = Convert.FromBase64String("A/u2bAGlBV91ByotxKC+wkGpMDFjFnixpfY5ul7YO1Aw5dIfBa3bhlNJWsTc2KMO22o0tw36D4+a0FUtHTQNaQ=="),
                    IsDeleted = false,
                    IsSystemData = true,
                    FileId = null,
                    IsTrial = false,
                },
                new User
                {
                    Id = 2,
                    Name = "Origin",
                    Surname = "User",
                    Email = "origin@test.com",
                    Password = "DBD9DCE9DB51E56E1468B18F44233EB1FF625ADCECAAE2D7E9776BC714AF69D2A360B57CDB7C4E098C6225543BF83C50DAEC23A8DAADF9212BADF6F26760911C",
                    Phone = "+905077352772",
                    Username = "originuser",
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow,
                    TrialExpirationDate = DateTime.UtcNow.AddDays(7),
                    ExpirationDate = DateTime.UtcNow.AddYears(1),
                    Salt = Convert.FromBase64String("A/u2bAGlBV91ByotxKC+wkGpMDFjFnixpfY5ul7YO1Aw5dIfBa3bhlNJWsTc2KMO22o0tw36D4+a0FUtHTQNaQ=="),
                    IsDeleted = false,
                    IsSystemData = true,
                    FileId = 1,
                    IsTrial = false,
                },
                new User
                {
                    Id = 3,
                    Name = "Heart",
                    Surname = "User",
                    Email = "heart@test.com",
                    Password = "DBD9DCE9DB51E56E1468B18F44233EB1FF625ADCECAAE2D7E9776BC714AF69D2A360B57CDB7C4E098C6225543BF83C50DAEC23A8DAADF9212BADF6F26760911C",
                    Phone = "+905077352772",
                    Username = "heartuser",
                    CreatedDate = DateTime.UtcNow,
                    TrialExpirationDate = DateTime.UtcNow.AddDays(7),
                    ExpirationDate = DateTime.UtcNow.AddYears(1),
                    Salt = Convert.FromBase64String("A/u2bAGlBV91ByotxKC+wkGpMDFjFnixpfY5ul7YO1Aw5dIfBa3bhlNJWsTc2KMO22o0tw36D4+a0FUtHTQNaQ=="),
                    IsDeleted = false,
                    IsSystemData = true,
                    FileId = 2,
                    IsActive = true,
                    IsTrial = false
                },
                new User
                {
                    Id = 4,
                    Name = "Family",
                    Surname = "User",
                    Email = "family@test.com",
                    Password = "DBD9DCE9DB51E56E1468B18F44233EB1FF625ADCECAAE2D7E9776BC714AF69D2A360B57CDB7C4E098C6225543BF83C50DAEC23A8DAADF9212BADF6F26760911C",
                    Phone = "+905077352772",
                    Username = "familyuser",
                    CreatedDate = DateTime.UtcNow,
                    TrialExpirationDate = DateTime.UtcNow.AddDays(7),
                    ExpirationDate = DateTime.UtcNow.AddYears(1),
                    Salt = Convert.FromBase64String("A/u2bAGlBV91ByotxKC+wkGpMDFjFnixpfY5ul7YO1Aw5dIfBa3bhlNJWsTc2KMO22o0tw36D4+a0FUtHTQNaQ=="),
                    IsDeleted = false,
                    IsSystemData = true,
                    FileId = 3,
                    IsActive = true,
                    IsTrial = false
                }
            );

            modelBuilder.Entity<UserRole>().HasData(
                //SuperAdmin User Role
                new UserRole
                {
                    Id = 1,
                    RoleId = 1,
                    UserId = 1,
                    IsDeleted = false
                },
                //Memory User Role
                new UserRole
                {
                    Id = 2,
                    RoleId = 2,
                    UserId = 2,
                    IsDeleted = false
                },
                //Tribute User Role
                new UserRole
                {
                    Id = 3,
                    RoleId = 3,
                    UserId = 3,
                    IsDeleted = false
                },
                //Eternal User Role
                new UserRole
                {
                    Id = 4,
                    RoleId = 4,
                    UserId = 4,
                    IsDeleted = false
                }
            );

            modelBuilder.Entity<UserPermission>().HasData(
                //SuperAdmin User Permissions
                new UserPermission { Id = 1, UserId = 1, PermissionId = 1, IsDeleted = false },
                new UserPermission { Id = 2, UserId = 1, PermissionId = 2, IsDeleted = false },
                new UserPermission { Id = 3, UserId = 1, PermissionId = 3, IsDeleted = false },
                new UserPermission { Id = 4, UserId = 1, PermissionId = 4, IsDeleted = false },
                new UserPermission { Id = 5, UserId = 1, PermissionId = 5, IsDeleted = false },
                new UserPermission { Id = 6, UserId = 1, PermissionId = 6, IsDeleted = false },
                new UserPermission { Id = 7, UserId = 1, PermissionId = 7, IsDeleted = false },
                new UserPermission { Id = 8, UserId = 1, PermissionId = 8, IsDeleted = false },
                new UserPermission { Id = 9, UserId = 1, PermissionId = 9, IsDeleted = false },
                new UserPermission { Id = 10, UserId = 1, PermissionId = 10, IsDeleted = false },
                new UserPermission { Id = 11, UserId = 1, PermissionId = 11, IsDeleted = false },
                new UserPermission { Id = 12, UserId = 1, PermissionId = 12, IsDeleted = false },
                new UserPermission { Id = 13, UserId = 1, PermissionId = 13, IsDeleted = false },
                new UserPermission { Id = 14, UserId = 1, PermissionId = 14, IsDeleted = false },
                new UserPermission { Id = 15, UserId = 1, PermissionId = 15, IsDeleted = false },
                new UserPermission { Id = 16, UserId = 1, PermissionId = 16, IsDeleted = false },
                new UserPermission { Id = 17, UserId = 1, PermissionId = 17, IsDeleted = false },
                new UserPermission { Id = 18, UserId = 1, PermissionId = 18, IsDeleted = false },
                new UserPermission { Id = 19, UserId = 1, PermissionId = 19, IsDeleted = false },
                new UserPermission { Id = 20, UserId = 1, PermissionId = 20, IsDeleted = false },
                new UserPermission { Id = 21, UserId = 1, PermissionId = 21, IsDeleted = false },
                new UserPermission { Id = 22, UserId = 1, PermissionId = 22, IsDeleted = false },
                new UserPermission { Id = 23, UserId = 1, PermissionId = 23, IsDeleted = false },
                new UserPermission { Id = 24, UserId = 1, PermissionId = 24, IsDeleted = false },
                new UserPermission { Id = 25, UserId = 1, PermissionId = 25, IsDeleted = false },
                new UserPermission { Id = 26, UserId = 1, PermissionId = 26, IsDeleted = false },
                new UserPermission { Id = 27, UserId = 1, PermissionId = 27, IsDeleted = false },
                new UserPermission { Id = 28, UserId = 1, PermissionId = 28, IsDeleted = false },
                new UserPermission { Id = 29, UserId = 1, PermissionId = 29, IsDeleted = false },
                new UserPermission { Id = 30, UserId = 1, PermissionId = 30, IsDeleted = false },
                new UserPermission { Id = 31, UserId = 1, PermissionId = 31, IsDeleted = false },
                new UserPermission { Id = 32, UserId = 1, PermissionId = 32, IsDeleted = false },
                new UserPermission { Id = 33, UserId = 1, PermissionId = 33, IsDeleted = false },
                new UserPermission { Id = 34, UserId = 1, PermissionId = 34, IsDeleted = false },
                new UserPermission { Id = 35, UserId = 1, PermissionId = 35, IsDeleted = false },
                new UserPermission { Id = 36, UserId = 1, PermissionId = 36, IsDeleted = false },
                new UserPermission { Id = 37, UserId = 1, PermissionId = 37, IsDeleted = false },
                new UserPermission { Id = 38, UserId = 1, PermissionId = 38, IsDeleted = false },
                new UserPermission { Id = 39, UserId = 1, PermissionId = 39, IsDeleted = false },
                new UserPermission { Id = 40, UserId = 1, PermissionId = 40, IsDeleted = false },
                new UserPermission { Id = 41, UserId = 1, PermissionId = 41, IsDeleted = false },
                //Memory User Permissions
                new UserPermission { Id = 42, UserId = 2, PermissionId = 1, IsDeleted = false },
                new UserPermission { Id = 43, UserId = 2, PermissionId = 2, IsDeleted = false },
                new UserPermission { Id = 44, UserId = 2, PermissionId = 3, IsDeleted = false },
                new UserPermission { Id = 45, UserId = 2, PermissionId = 4, IsDeleted = false },
                new UserPermission { Id = 46, UserId = 2, PermissionId = 5, IsDeleted = false },
                new UserPermission { Id = 47, UserId = 2, PermissionId = 6, IsDeleted = false },
                new UserPermission { Id = 48, UserId = 2, PermissionId = 7, IsDeleted = false },
                new UserPermission { Id = 49, UserId = 2, PermissionId = 8, IsDeleted = false },
                new UserPermission { Id = 50, UserId = 2, PermissionId = 9, IsDeleted = false },
                new UserPermission { Id = 51, UserId = 2, PermissionId = 10, IsDeleted = false },
                new UserPermission { Id = 52, UserId = 2, PermissionId = 11, IsDeleted = false },
                new UserPermission { Id = 53, UserId = 2, PermissionId = 12, IsDeleted = false },
                new UserPermission { Id = 54, UserId = 2, PermissionId = 13, IsDeleted = false },
                new UserPermission { Id = 55, UserId = 2, PermissionId = 14, IsDeleted = false },
                new UserPermission { Id = 56, UserId = 2, PermissionId = 15, IsDeleted = false },
                new UserPermission { Id = 57, UserId = 2, PermissionId = 16, IsDeleted = false },
                new UserPermission { Id = 58, UserId = 2, PermissionId = 17, IsDeleted = false },
                new UserPermission { Id = 59, UserId = 2, PermissionId = 18, IsDeleted = false },
                new UserPermission { Id = 60, UserId = 2, PermissionId = 19, IsDeleted = false },
                new UserPermission { Id = 61, UserId = 2, PermissionId = 20, IsDeleted = false },
                new UserPermission { Id = 62, UserId = 2, PermissionId = 21, IsDeleted = false },
                new UserPermission { Id = 63, UserId = 2, PermissionId = 22, IsDeleted = false },
                new UserPermission { Id = 64, UserId = 2, PermissionId = 23, IsDeleted = false },
                new UserPermission { Id = 65, UserId = 2, PermissionId = 24, IsDeleted = false },
                new UserPermission { Id = 66, UserId = 2, PermissionId = 25, IsDeleted = false },
                new UserPermission { Id = 67, UserId = 2, PermissionId = 26, IsDeleted = false },
                new UserPermission { Id = 68, UserId = 2, PermissionId = 27, IsDeleted = false },
                new UserPermission { Id = 69, UserId = 2, PermissionId = 28, IsDeleted = false },
                new UserPermission { Id = 70, UserId = 2, PermissionId = 29, IsDeleted = false },
                new UserPermission { Id = 71, UserId = 2, PermissionId = 30, IsDeleted = false },
                new UserPermission { Id = 72, UserId = 2, PermissionId = 31, IsDeleted = false },
                new UserPermission { Id = 73, UserId = 2, PermissionId = 32, IsDeleted = false },
                new UserPermission { Id = 74, UserId = 2, PermissionId = 33, IsDeleted = false },
                new UserPermission { Id = 75, UserId = 2, PermissionId = 34, IsDeleted = false },
                new UserPermission { Id = 76, UserId = 2, PermissionId = 35, IsDeleted = false },
                new UserPermission { Id = 77, UserId = 2, PermissionId = 36, IsDeleted = false },
                new UserPermission { Id = 78, UserId = 2, PermissionId = 37, IsDeleted = false },
                new UserPermission { Id = 79, UserId = 2, PermissionId = 38, IsDeleted = false },
                new UserPermission { Id = 80, UserId = 2, PermissionId = 39, IsDeleted = false },
                new UserPermission { Id = 81, UserId = 2, PermissionId = 40, IsDeleted = false },
                new UserPermission { Id = 82, UserId = 2, PermissionId = 41, IsDeleted = false },
                //Tribute User Permissions
                new UserPermission { Id = 83, UserId = 3, PermissionId = 1, IsDeleted = false },
                new UserPermission { Id = 84, UserId = 3, PermissionId = 2, IsDeleted = false },
                new UserPermission { Id = 85, UserId = 3, PermissionId = 3, IsDeleted = false },
                new UserPermission { Id = 86, UserId = 3, PermissionId = 4, IsDeleted = false },
                new UserPermission { Id = 87, UserId = 3, PermissionId = 5, IsDeleted = false },
                new UserPermission { Id = 88, UserId = 3, PermissionId = 6, IsDeleted = false },
                new UserPermission { Id = 89, UserId = 3, PermissionId = 7, IsDeleted = false },
                new UserPermission { Id = 90, UserId = 3, PermissionId = 8, IsDeleted = false },
                new UserPermission { Id = 91, UserId = 3, PermissionId = 9, IsDeleted = false },
                new UserPermission { Id = 92, UserId = 3, PermissionId = 10, IsDeleted = false },
                new UserPermission { Id = 93, UserId = 3, PermissionId = 11, IsDeleted = false },
                new UserPermission { Id = 94, UserId = 3, PermissionId = 12, IsDeleted = false },
                new UserPermission { Id = 95, UserId = 3, PermissionId = 13, IsDeleted = false },
                new UserPermission { Id = 96, UserId = 3, PermissionId = 14, IsDeleted = false },
                new UserPermission { Id = 97, UserId = 3, PermissionId = 15, IsDeleted = false },
                new UserPermission { Id = 98, UserId = 3, PermissionId = 16, IsDeleted = false },
                new UserPermission { Id = 99, UserId = 3, PermissionId = 17, IsDeleted = false },
                new UserPermission { Id = 100, UserId = 3, PermissionId = 18, IsDeleted = false },
                new UserPermission { Id = 101, UserId = 3, PermissionId = 19, IsDeleted = false },
                new UserPermission { Id = 102, UserId = 3, PermissionId = 20, IsDeleted = false },
                new UserPermission { Id = 103, UserId = 3, PermissionId = 21, IsDeleted = false },
                new UserPermission { Id = 104, UserId = 3, PermissionId = 22, IsDeleted = false },
                new UserPermission { Id = 105, UserId = 3, PermissionId = 23, IsDeleted = false },
                new UserPermission { Id = 106, UserId = 3, PermissionId = 24, IsDeleted = false },
                new UserPermission { Id = 107, UserId = 3, PermissionId = 25, IsDeleted = false },
                new UserPermission { Id = 108, UserId = 3, PermissionId = 26, IsDeleted = false },
                new UserPermission { Id = 109, UserId = 3, PermissionId = 27, IsDeleted = false },
                new UserPermission { Id = 110, UserId = 3, PermissionId = 28, IsDeleted = false },
                new UserPermission { Id = 111, UserId = 3, PermissionId = 29, IsDeleted = false },
                new UserPermission { Id = 112, UserId = 3, PermissionId = 30, IsDeleted = false },
                new UserPermission { Id = 113, UserId = 3, PermissionId = 31, IsDeleted = false },
                new UserPermission { Id = 114, UserId = 3, PermissionId = 32, IsDeleted = false },
                new UserPermission { Id = 115, UserId = 3, PermissionId = 33, IsDeleted = false },
                new UserPermission { Id = 116, UserId = 3, PermissionId = 34, IsDeleted = false },
                new UserPermission { Id = 117, UserId = 3, PermissionId = 35, IsDeleted = false },
                new UserPermission { Id = 118, UserId = 3, PermissionId = 36, IsDeleted = false },
                new UserPermission { Id = 119, UserId = 3, PermissionId = 37, IsDeleted = false },
                new UserPermission { Id = 120, UserId = 3, PermissionId = 38, IsDeleted = false },
                new UserPermission { Id = 121, UserId = 3, PermissionId = 39, IsDeleted = false },
                new UserPermission { Id = 122, UserId = 3, PermissionId = 40, IsDeleted = false },
                new UserPermission { Id = 123, UserId = 3, PermissionId = 41, IsDeleted = false },
                //Eternal User Permissions
                new UserPermission { Id = 124, UserId = 4, PermissionId = 1, IsDeleted = false },
                new UserPermission { Id = 125, UserId = 4, PermissionId = 2, IsDeleted = false },
                new UserPermission { Id = 126, UserId = 4, PermissionId = 3, IsDeleted = false },
                new UserPermission { Id = 127, UserId = 4, PermissionId = 4, IsDeleted = false },
                new UserPermission { Id = 128, UserId = 4, PermissionId = 5, IsDeleted = false },
                new UserPermission { Id = 129, UserId = 4, PermissionId = 6, IsDeleted = false },
                new UserPermission { Id = 130, UserId = 4, PermissionId = 7, IsDeleted = false },
                new UserPermission { Id = 131, UserId = 4, PermissionId = 8, IsDeleted = false },
                new UserPermission { Id = 132, UserId = 4, PermissionId = 9, IsDeleted = false },
                new UserPermission { Id = 133, UserId = 4, PermissionId = 10, IsDeleted = false },
                new UserPermission { Id = 134, UserId = 4, PermissionId = 11, IsDeleted = false },
                new UserPermission { Id = 135, UserId = 4, PermissionId = 12, IsDeleted = false },
                new UserPermission { Id = 136, UserId = 4, PermissionId = 13, IsDeleted = false },
                new UserPermission { Id = 137, UserId = 4, PermissionId = 14, IsDeleted = false },
                new UserPermission { Id = 138, UserId = 4, PermissionId = 15, IsDeleted = false },
                new UserPermission { Id = 139, UserId = 4, PermissionId = 16, IsDeleted = false },
                new UserPermission { Id = 140, UserId = 4, PermissionId = 17, IsDeleted = false },
                new UserPermission { Id = 141, UserId = 4, PermissionId = 18, IsDeleted = false },
                new UserPermission { Id = 142, UserId = 4, PermissionId = 19, IsDeleted = false },
                new UserPermission { Id = 143, UserId = 4, PermissionId = 20, IsDeleted = false },
                new UserPermission { Id = 144, UserId = 4, PermissionId = 21, IsDeleted = false },
                new UserPermission { Id = 145, UserId = 4, PermissionId = 22, IsDeleted = false },
                new UserPermission { Id = 146, UserId = 4, PermissionId = 23, IsDeleted = false },
                new UserPermission { Id = 147, UserId = 4, PermissionId = 24, IsDeleted = false },
                new UserPermission { Id = 148, UserId = 4, PermissionId = 25, IsDeleted = false },
                new UserPermission { Id = 149, UserId = 4, PermissionId = 26, IsDeleted = false },
                new UserPermission { Id = 150, UserId = 4, PermissionId = 27, IsDeleted = false },
                new UserPermission { Id = 151, UserId = 4, PermissionId = 28, IsDeleted = false },
                new UserPermission { Id = 152, UserId = 4, PermissionId = 29, IsDeleted = false },
                new UserPermission { Id = 153, UserId = 4, PermissionId = 30, IsDeleted = false },
                new UserPermission { Id = 154, UserId = 4, PermissionId = 31, IsDeleted = false },
                new UserPermission { Id = 155, UserId = 4, PermissionId = 32, IsDeleted = false },
                new UserPermission { Id = 156, UserId = 4, PermissionId = 33, IsDeleted = false },
                new UserPermission { Id = 157, UserId = 4, PermissionId = 34, IsDeleted = false },
                new UserPermission { Id = 158, UserId = 4, PermissionId = 35, IsDeleted = false },
                new UserPermission { Id = 159, UserId = 4, PermissionId = 36, IsDeleted = false },
                new UserPermission { Id = 160, UserId = 4, PermissionId = 37, IsDeleted = false },
                new UserPermission { Id = 161, UserId = 4, PermissionId = 38, IsDeleted = false },
                new UserPermission { Id = 162, UserId = 4, PermissionId = 39, IsDeleted = false },
                new UserPermission { Id = 163, UserId = 4, PermissionId = 40, IsDeleted = false },
                new UserPermission { Id = 164, UserId = 4, PermissionId = 41, IsDeleted = false },
                new UserPermission { Id = 165, UserId = 1, PermissionId = 42, IsDeleted = false },
                new UserPermission { Id = 166, UserId = 2, PermissionId = 42, IsDeleted = false },
                new UserPermission { Id = 167, UserId = 3, PermissionId = 42, IsDeleted = false },
                new UserPermission { Id = 168, UserId = 4, PermissionId = 42, IsDeleted = false }
            );
        }

    }
}
