// <auto-generated />
using System;
using MemoryManagement.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MemoryManagement.Migrations
{
    [DbContext(typeof(MemoryManagementContext))]
    [Migration("20251119104704_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MemoryManagement.Entity.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EnName = "Bird",
                            IsDeleted = false,
                            Name = "Kuş"
                        },
                        new
                        {
                            Id = 2L,
                            EnName = "Cat",
                            IsDeleted = false,
                            Name = "Kedi"
                        },
                        new
                        {
                            Id = 3L,
                            EnName = "Dog",
                            IsDeleted = false,
                            Name = "Köpek"
                        },
                        new
                        {
                            Id = 4L,
                            EnName = "Fish",
                            IsDeleted = false,
                            Name = "Balık"
                        },
                        new
                        {
                            Id = 5L,
                            EnName = "Hamster",
                            IsDeleted = false,
                            Name = "Fare"
                        },
                        new
                        {
                            Id = 6L,
                            EnName = "Horse",
                            IsDeleted = false,
                            Name = "At"
                        },
                        new
                        {
                            Id = 7L,
                            EnName = "Turtle",
                            IsDeleted = false,
                            Name = "Kaplumbağa"
                        });
                });

            modelBuilder.Entity("MemoryManagement.Entity.Memory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("DeathDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpenToComment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Memories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BirthDate = new DateOnly(2023, 11, 12),
                            CategoryId = 2L,
                            DeathDate = new DateOnly(2024, 8, 28),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = false,
                            Name = "Queenie",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5353),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            BirthDate = new DateOnly(2020, 4, 4),
                            CategoryId = 3L,
                            DeathDate = new DateOnly(2025, 5, 5),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = false,
                            Name = "Ringo",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5360),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            BirthDate = new DateOnly(2024, 1, 12),
                            CategoryId = 4L,
                            DeathDate = new DateOnly(2024, 8, 18),
                            IsDeleted = false,
                            IsOpenToComment = false,
                            IsPrivate = false,
                            Name = "Bubbles",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5362),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 4L
                        },
                        new
                        {
                            Id = 4L,
                            BirthDate = new DateOnly(2018, 2, 14),
                            CategoryId = 6L,
                            DeathDate = new DateOnly(2024, 11, 24),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = true,
                            Name = "George",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5364),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            BirthDate = new DateOnly(2018, 2, 14),
                            CategoryId = 6L,
                            DeathDate = new DateOnly(2024, 11, 24),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = false,
                            Name = "Fredy",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5422),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            BirthDate = new DateOnly(2018, 2, 14),
                            CategoryId = 6L,
                            DeathDate = new DateOnly(2024, 11, 24),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = false,
                            Name = "Hato",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5424),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            BirthDate = new DateOnly(2018, 2, 14),
                            CategoryId = 6L,
                            DeathDate = new DateOnly(2024, 11, 24),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = true,
                            Name = "Aaaaa",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5426),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            BirthDate = new DateOnly(2018, 2, 14),
                            CategoryId = 6L,
                            DeathDate = new DateOnly(2024, 11, 24),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = false,
                            Name = "Bbbbbb",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5427),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            BirthDate = new DateOnly(2018, 2, 14),
                            CategoryId = 6L,
                            DeathDate = new DateOnly(2024, 11, 24),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = false,
                            Name = "Cccccc",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5429),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 10L,
                            BirthDate = new DateOnly(2018, 2, 14),
                            CategoryId = 6L,
                            DeathDate = new DateOnly(2024, 11, 24),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = false,
                            Name = "Ddddddd",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5430),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            BirthDate = new DateOnly(2018, 2, 14),
                            CategoryId = 6L,
                            DeathDate = new DateOnly(2024, 11, 24),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = false,
                            Name = "Eeeeeee",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5432),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 12L,
                            BirthDate = new DateOnly(2018, 2, 14),
                            CategoryId = 6L,
                            DeathDate = new DateOnly(2024, 11, 24),
                            IsDeleted = false,
                            IsOpenToComment = true,
                            IsPrivate = false,
                            Name = "Ffffff",
                            PostDate = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5433),
                            Text = "Our precious Queenie crossed the Rainbow Bridge at 13 years old, leaving behind gentle pawprints on our hearts. Graceful, kind and full of quiet love, she filled our home with warmth and calm. Her soft purrs, curious eyes and tender ways brought comfort to every day and joy to every corner. Though the house feels still without her, we see her everywhere :- in the sunlight on the floor, in the quiet of the evening, and in every happy memory she gave us. Sleep softly, dear Queenie. You’ll always be part of our hearts and our home. Forever loved and sadly missed by Bryan, Lisa and Sarah\r\n",
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("MemoryManagement.Entity.MemoryComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("MemoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId");

                    b.ToTable("MemoryComments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Comment = "Bir bir yorumdur.",
                            Date = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5510),
                            IsDeleted = false,
                            MemoryId = 1L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 2L,
                            Comment = "Bir bir yorumdur. (2)",
                            Date = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5516),
                            IsDeleted = false,
                            MemoryId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Comment = "Bir bir yorumdur. (3)",
                            Date = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5517),
                            IsDeleted = false,
                            MemoryId = 1L,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 4L,
                            Comment = "Bir bir yorumdur. (4)",
                            Date = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5518),
                            IsDeleted = false,
                            MemoryId = 1L,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("MemoryManagement.Entity.MemoryFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<long>("MemoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId");

                    b.ToTable("MemoryFiles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FileId = 1L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            FileId = 2L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            FileId = 3L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            FileId = 4L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            FileId = 5L,
                            IsDeleted = false,
                            IsPrimary = false,
                            MemoryId = 4L
                        },
                        new
                        {
                            Id = 6L,
                            FileId = 6L,
                            IsDeleted = false,
                            IsPrimary = false,
                            MemoryId = 4L
                        },
                        new
                        {
                            Id = 7L,
                            FileId = 2L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 6L
                        },
                        new
                        {
                            Id = 8L,
                            FileId = 3L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 7L
                        },
                        new
                        {
                            Id = 9L,
                            FileId = 1L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 8L
                        },
                        new
                        {
                            Id = 10L,
                            FileId = 4L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 9L
                        },
                        new
                        {
                            Id = 11L,
                            FileId = 6L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 10L
                        },
                        new
                        {
                            Id = 12L,
                            FileId = 5L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 11L
                        },
                        new
                        {
                            Id = 13L,
                            FileId = 6L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 12L
                        },
                        new
                        {
                            Id = 14L,
                            FileId = 6L,
                            IsDeleted = false,
                            IsPrimary = true,
                            MemoryId = 5L
                        });
                });

            modelBuilder.Entity("MemoryManagement.Entity.MemoryLike", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("MemoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId");

                    b.ToTable("MemoryLikes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Date = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5544),
                            IsDeleted = false,
                            MemoryId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Date = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5545),
                            IsDeleted = false,
                            MemoryId = 1L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            Date = new DateTime(2025, 11, 19, 10, 47, 4, 190, DateTimeKind.Utc).AddTicks(5546),
                            IsDeleted = false,
                            MemoryId = 1L,
                            UserId = 4L
                        });
                });

            modelBuilder.Entity("MemoryManagement.Entity.Memory", b =>
                {
                    b.HasOne("MemoryManagement.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MemoryManagement.Entity.MemoryComment", b =>
                {
                    b.HasOne("MemoryManagement.Entity.Memory", "Memory")
                        .WithMany()
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("MemoryManagement.Entity.MemoryFile", b =>
                {
                    b.HasOne("MemoryManagement.Entity.Memory", "Memory")
                        .WithMany()
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("MemoryManagement.Entity.MemoryLike", b =>
                {
                    b.HasOne("MemoryManagement.Entity.Memory", "Memory")
                        .WithMany()
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });
#pragma warning restore 612, 618
        }
    }
}
